---

- name: Include Variables
  hosts: localhost
  gather_facts: false
  tasks:
    - include_vars: vars/main.yml

- name: DeployServer
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add DeployServer to host group
      add_host: hostname={{ DeployServer }} groupname=deploy_server

- name: ReportServers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add ReportServers to host group
      add_host: hostname={{ item }} groupname=report_server
      with_items: "ReportServers.split(',')"

- name: FE Servers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add FE Servers to host group
      add_host: hostname={{ item }} groupname=fe_servers
      with_items: "FEServers.split(',')"

- name: BE Servers
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Add BE Servers to host group
      add_host: hostname={{ item }} groupname=be_servers
      with_items: "BEServers.split(',')"

- name: Include Variables
  hosts: deploy_server:report_server:fe_servers:be_servers
  gather_facts: false
  tasks:
    - include_vars: vars/main.yml

- name: All Servers
  hosts: deploy_server:report_server:fe_servers:be_servers
  gather_facts: false
  tasks:
    - name: Update CRM Reg Keys
      script: files/crmRegUpdate.ps1 {{AGListener}} {{Domain}}

- name: All Servers
  hosts: deploy_server:report_server:fe_servers:be_servers
  gather_facts: false
  tasks:
    - name: Reboot All Servers
      raw: shutdown -r -f

- name: All Servers
  hosts: deploy_server:report_server:fe_servers:be_servers
  gather_facts: false
  tasks:
    - name: wait for All Servers to reboot
      local_action:
        module: wait_for
        host: "{{ ansible_ssh_host|default(inventory_hostname) }}"
        port: "{{ ansible_ssh_port|default(5985) }}"
        delay: 90
        timeout: 600
        state: started

















